# Hearing Sense configuration

input_audio_sensor:
  # Parametri di registrazione
  input_audio_sensor_index:               36               # 1, 15, 36, 61 Id del dispositivo da urilizzare come input audio device vedi [Dev Tools] "INPUT_AUDIO_DEVICES.py"
  input_audio_sensor_bits_format:         16               # 16 o 32-bit per sample
  input_audio_sensor_channels:            1                # Audio mono
  input_audio_sensor_rate:                48000            # Frequenza di campionamento (Hz)
  input_audio_sensor_chunk:               2048             # Dimensione dei blocchi di lettura (512, 1024, 2048 o 4096)
  input_audio_sensor_max_record_duration: 5                # Durata della registrazione (secondi)
  input_audio_sensor_output_path:         "output.wav"     # File audio che rappresenta lo stimolo uditivo

speech_recognition:
  model_01:                               "speechbrain/spkrec-xvect-voxceleb"
  model_02:                               "speechbrain/asr-wav2vec2-libri"
  energy_threshold:                       300              # minimum audio energy to consider for recording
  dynamic_energy_threshold:               True
  dynamic_energy_adjustment_damping:      0.15
  dynamic_energy_ratio:                   1.5  
  pause_threshold:                        0.8              # seconds of non-speaking audio before a phrase is considered complete
  operation_timeout:                      None             # seconds after an internal operation (e.g., an API request) starts before it times out, or ``None`` for no timeout

speaker_recognition:
  focus_speaker_id: "speaker1"
  # threshold
  # Soglia di riconoscimento parlante
  threshold: 0.75  

transcription:
  # min_words
  # Minimo numero di parole per considerare "senso compiuto"
  min_words: 3  
  # whisper_model
  # Modello Whisper da utilizzare (tiny   - Molto veloce, ma meno accurato. 
  #                                base   - Bilanciato per velocità e precisione.
  #                                small  - Più accurato, ma più lento.
  #                                medium - Alta precisione, richiede più risorse.
  #                                large  - Massima precisione, utilizza molta memoria.
  whisper_model_name: "medium"  